import {Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";



const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weights: [400, 500, 700], 
  display: 'swap', 
});

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
